FROM almalinux:8
RUN adduser venky 
USER venky
WORKDIR /tmp
RUN echo "if we use the RUN to create the and use that directory it won't ctreate and it will goto the default directory " > restfile.txt
CMD ["sleep", "100"]